name = "book-inventory"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "book-inventory"
database_id = "0c1f6b32-a6b0-4c1a-b1d1-5aa37e17f4cc"
